name: valoro
description: A new money management application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  firebase_core: ^0.4.3+1
  provider: ^4.0.1
  font_awesome_flutter: ^8.5.0
  cached_network_image: ^1.1.3
  auto_size_text: ^2.1.0
  google_fonts: ^0.2.0
  contacts_service: ^0.3.10
  flutter_typeahead: ^1.7.0
  permission_handler: '^4.0.0'
  flutter_datetime_picker: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - mangekyo-sharingan.flr