name: valoro
description: A new money management application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
  cloud_firestore: ^0.12.5+2
  firebase_auth: ^0.11.1+7
  google_sign_in: ^4.0.2
  firebase_core: ^0.4.0
  provider: ^3.0.0
  font_awesome_flutter: ^8.4.0
  cached_network_image: ^0.8.0
  auto_size_text: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - mangekyo-sharingan.flr

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
    - family: RobotoSlab
      fonts:
        - asset: fonts/Roboto_Slab/RobotoSlab-Regular.ttf
        - asset: fonts/Roboto_Slab/RobotoSlab-Bold.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto_Mono/RobotoMono-Medium.ttf
        - asset: fonts/Roboto_Mono/RobotoMono-Light.ttf